Router
xchanti124/kelvir-frontend pull request #12
Opened 2023-02-27 21:11 UTC by FlyingRatMan

2023-02-27 21:20 UTC, xchanti124 requested changes
Everything looks fine to me, except that it looks like this branch is behind main, you can just run `git pull origin main --rebase` to get the branch up-to-date with main.

2023-02-27 21:20 UTC, xchanti124 commented on src/components/Error404.js
> +const Error404 = () => {
Prettier wasn't applied to this file.

2023-02-28 19:19 UTC, FlyingRatMan commented on src/components/Error404.js
> +const Error404 = () => {
uh true I forgot to run it...will do it

2023-03-02 21:38 UTC, xchanti124 approved these changes

2023-03-03 14:45 UTC, merged