About page
xchanti124/kelvir-frontend pull request #14
Opened 2023-03-10 21:38 UTC by meeragk99

2023-03-12 14:27 UTC, xchanti124 reviewed
Looks good to me, however, I think you should wait for Olya's approval.

2023-03-13 16:30 UTC, FlyingRatMan requested changes
There are things to be removed.

2023-03-13 16:30 UTC, FlyingRatMan commented on package.json
> +    "express-body-parser-error-handler": "^1.0.4",
We don't need this "express-body-parser-error-handler". Could you please delete it? `npm uninstall express-body-parser-error-handler`

2023-03-13 16:30 UTC, FlyingRatMan commented on package.json
> +    "react-hook-form": "^7.42.1",
We don't need this "react-hook-form". Could you please delete it? `npm uninstall react-hook-form`

2023-03-13 16:30 UTC, FlyingRatMan commented on src/App.js
> +        <Route path={"/404"} element={<Error404 />} />
Are we redirecting explicitly to `/404` anywhere? We already have a fallback for undefined routes.

2023-03-13 16:30 UTC, FlyingRatMan commented on src/components/About.js
> +      <img src="/path/to/image" alt="Image description" />
This should be removed.

2023-03-13 16:30 UTC, FlyingRatMan commented on src/components/About.js
> +      <button aria-label="Click me">Click me</button>
This should be removed.

2023-03-16 18:29 UTC, FlyingRatMan approved these changes

2023-03-16 19:29 UTC, merged