Search bar component
xchanti124/kelvir-frontend pull request #4
Opened 2023-01-22 16:41 UTC by meeragk99

2023-01-22 16:52 UTC, xchanti124 approved these changes

2023-01-22 22:29 UTC, FlyingRatMan commented
Why is this a pull request? Is this a pull request from Meera? And why there is only my commits that are already merged? 
I don't understand what's happening here

2023-01-23 06:20 UTC, xchanti124 commented
I think Meera was a little confused... let's go over the steps on how to make a correct PR in the meeting today evening.

2023-01-23 15:12 UTC, xchanti124 requested changes
Let's go over this tonight!

2023-01-25 10:40 UTC, closed without merging